/**:
  ros__parameters:
    # Standalone example params file for GX3, GX4, GX/CX5, RQ1 and GQ7 series devices
    # Note: Feature support is device-dependent and some of the following settings may have no affect on your device.
    # Please consult your device's documentation for supported features
    
    # ****************************************************************** 
    # NOTE: This file is formatted to work with ROS and will not work if specified as the params_file argument in ROS2.
    #       If you want to override parameters for ROS2, start with https://github.com/LORD-MicroStrain/microstrain_inertial/blob/ros2/microstrain_inertial_driver/config/empty.yml
    # ****************************************************************** 
    
    # ****************************************************************** 
    # General Settings 
    # ****************************************************************** 
    
    # port is the main port that the device will communicate over. For all devices except the GQ7, this is the only available port.
    # aux_port is only available for the GQ7 and is only needed when streaming RTCM corrections to the device from ROS, or if you want to publish NMEA sentences from this node
    port        : "/dev/ttyACM0"
    aux_port    : "/dev/ttyACM1"
    baudrate    : 115200
    debug       : False
    diagnostics : False
    
    # If set to true, this will configure the requested baudrate on the device. Note that this only has an affect when the device is connected via serial
    set_baud : False
    
    # Frame IDs used in the different messages. By default these are set to arbitrary strings as not to interfere with other ROS services.
    # For more information on common frame IDs, check out: https://www.ros.org/reps/rep-0105.html
    #
    # filter_frame_id and filter_child_frame_id are specifically useful as the node will also publish a transform to the /tf topic
    # that contains the transform between these two frames. Many ROS tools such as RViz will use the /tf topic to display things like robot position.
    imu_frame_id          : "imu_link"
    filter_child_frame_id : "imu_link"
    
    # The directory to store the raw data file (no trailing '/')
    raw_file_directory : "/tmp"
    
    
    # ****************************************************************** 
    # IMU Settings 
    # ****************************************************************** 
    imu_data_rate : 100
